"""
EVIDRA — Hotspots API.
"""
from fastapi import APIRouter, Depends
from core.database import db
from api.auth import get_current_user

router = APIRouter(prefix="/cases/{case_id}/hotspots", tags=["Hotspots"])

@router.get("")
async def get_hotspots(case_id: str, current_user: dict = Depends(get_current_user)):
    """Get ranked hotspots generated by the Tier 4 fusion engine."""
    rows = await db.fetch("SELECT * FROM hotspots WHERE case_id=$1 ORDER BY rank ASC", case_id)
    return {"hotspots": [{**dict(r), "time_start": str(r["time_start"]), "time_end": str(r["time_end"])} for r in rows]}
